### PR TITLE
Ensure pod is scheduled on a control-plane node

### PR DESCRIPTION
**Pull request by 34fathombelow**
Added a nodeAffinity to manifest to ensure all pods with be scheduled onto a control-plane node. Also added tolerations to allow pods to be scheduled tainted control-planes.  Updated imagePullPolicy to Always,  will only download the images if current image does not match the digest on the registry.

Please review and test.

### CODE REVIEW

**Comment by chengkuangan** [comment]
@34fathombelow 

The yaml looks fine. Do you have the following warning (`Warning  FailedMount`) when you run the Pod in the cluster?
The pod seems to run without problem but this warning shows up when you do a `kubectl describe pod`

```
  Normal   Pulled       14s              kubelet            Successfully pulled image ...
  Normal   Created      14s              kubelet            Created container etcdbk
  Normal   Started      13s              kubelet            Started container etcdbk
  Warning  FailedMount  4s (x2 over 5s)  kubelet            MountVolume.SetUp failed for volume "kube-api-access-m8z6b" : object "etcdbk"/"kube-root-ca.crt" not registered
```

**Comment by 34fathombelow** [comment]
@chengkuangan

What are you using to test?   Which node did the pod get assigned to?

**Comment by chengkuangan** [comment]
@34fathombelow 

It assigned to control-plane. works without issue though, just curious what is this warning about ...

**Comment by chengkuangan** [comment]
@34fathombelow 

found it. need to add the following at the spec
```
automountServiceAccountToken: false
```
refer here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server

**Comment by chengkuangan** [comment]
[This](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server) could be it but not really solving .. it caused API connection failed

Maybe can just ignore the warning since `etcdctl` is running without problem

**Comment by chengkuangan** [comment]
> [This](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server) could be it but not really solving .. it caused API connection failed
> 
> Maybe can just ignore the warning since `etcdctl` is running without problem

what do you think?

**Comment by chengkuangan** [comment]
continue tomorrow, it's midnight, going to bed.

**Comment by 34fathombelow** [comment]
Im going to look into this today.  I would really not like to have any warnings,  you will have an answer first thing when you wake up.

**Comment by 34fathombelow** [comment]
I did add a serviceaccount for `etcdbk.yaml`  It is not fixing the FailedMount warning but does add a bit of security.  Any additional pods added to the etcdbk namespace would not be able to inherit the elevated clusterRole permissions system-wide.

I think we can ignore this error for now,  we do not need to access the api within the pod.

**Comment by chengkuangan** [comment]
@34fathombelow 

I meshed up the merge with my local files ... fixed them manually back to the latest changes. You may want to double check. Sorry for the mesh.

Also, updated the run-backup.sh to just snapshot the current node the pod is running. Reflected the changes in etcdbk.yaml with additional NODE_NAME env variable.

Have a nice evening to you.

**Comment by 34fathombelow** [comment]
@chengkuangan 
I saw that, no worries all looks good to me.  

Should we change line #75 in run-backup.sh
From:  ```for FILE in `ls ${BAKCUP_PATH}/$1* | sort -r`; do ```
To: ```for FILE in `ls -tr  ${BAKCUP_PATH}/$1* ; do ```

This would sort files by modification time in reverse, rather than by alphabetically.

**Comment by chengkuangan** [comment]
Sure

**Comment by chengkuangan** [comment]
> @chengkuangan I saw that, no worries all looks good to me.
> 
> Should we change line #75 in run-backup.sh From: `` for FILE in `ls ${BAKCUP_PATH}/$1* | sort -r`; do `` To: `` for FILE in `ls -tr ${BAKCUP_PATH}/$1* ; do ``
> 
> This would sort files by modification time in reverse, rather than by alphabetically.

Changed and committed. Actually it does not matter because we name the snapshot files with datetime stamp

**Pull request merged**
